name: Iterate through multiple files to create links

on:
  workflow_dispatch:

jobs:
  itercopy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Make some files for us to iterate through
      run: |
        mkdir -p dist/installers
        touch dist/installers/brim_amd64.deb
        touch dist/installers/brim_x86_64.rpm
    - name: Pretend we have a bucket path
      run: echo "BUCKET_PATH=gs://${{ secrets.GCLOUD_BUCKET_RELEASES }}/brim/itercopy/linux" >> $GITHUB_ENV
    - name: Set publicly-available bucket path
      run: echo "PUBLIC_BUCKET_PATH=${BUCKET_PATH/gs:\/\//https://storage.googleapis.com/}" >> $GITHUB_ENV
    - name: Iterate through files
      run: |
        echo "SLACK_TEXT<<EOF" >> $GITHUB_ENV
        echo "New Linux release available -" >> $GITHUB_ENV
        for FILENAME in $(find dist/installers -type f -exec basename {} \;)
        do
          echo "\n<${{ env.PUBLIC_BUCKET_PATH }}/$FILENAME|${{ env.BUCKET_PATH }}/$FILENAME>" >> $GITHUB_ENV
        done
        echo "EOF" >> $GITHUB_ENV
    - name: Inform Slack users
      uses: tiloio/slack-webhook-action@v1.1.2
      with:
        slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_BRIMLABS_RELEASES }}
        slack_json: '{
                       "username": "release-automation",
                       "text": "${{ env.SLACK_TEXT }}"
                     }'

